export const DB_TABLES = {
  AUTH_TOKENS: 'auth_tokens',
  USERS: 'users',
  BALANCES: 'balances',
  RIDES: 'rides',
  TRIPS: 'trips',
  MESSAGES: 'messages',
  CARDS: 'cards',
  RENTALS: 'rentals',
  CAR_BRANDS: 'car_brands',
  DRIVER_EARNINGS: 'driver_earnings',
  DRIVER_LEDGER_ENTRIES: 'driver_ledger_entries',
  DRIVER_RIDE_OFFERS: 'driver_ride_offers',
  DRIVER_ONLINE_SESSIONS: 'driver_online_sessions',
  ACTIVITIES: 'activities',
  REFERRALS: 'referrals',
  WALLET_TRANSACTIONS: 'wallet_transactions',
  BANK_ACCOUNTS: 'bank_accounts',
  PAYOUT_REQUESTS: 'payout_requests',
  FINANCIAL_SETTINGS: 'financial_settings',
  DRIVER_FINANCIAL_STATES: 'driver_financial_states',
  PUSH_CAMPAIGNS: 'push_campaigns',
};
