export const DB_TABLES = {
  AUTH_TOKENS: 'auth_tokens',
  USERS: 'users',
  BALANCES: 'balances',
  RIDES: 'rides',
  TRIPS: 'trips',
  MESSAGES: 'messages',
  CARDS: 'cards',
  RENTALS: 'rentals',
  CAR_BRANDS: 'car_brands',
  DRIVER_EARNINGS: 'driver_earnings',
  DRIVER_LEDGER_ENTRIES: 'driver_ledger_entries',
  DRIVER_RIDE_OFFERS: 'driver_ride_offers',
  DRIVER_ONLINE_SESSIONS: 'driver_online_sessions',
  ACTIVITIES: 'activities',
};
